# Generated by Django 5.0 on 2024-02-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0033_alter_floor_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.block', verbose_name='Выбрать блок'),
        ),
    ]
