# Generated by Django 5.0 on 2024-02-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0034_alter_floor_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentosob',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osob', to='apartment.category'),
        ),
    ]
