# Generated by Django 5.0 on 2024-02-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_alter_advantagestwo_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enviromenttitle',
            unique_together=set(),
        ),
    ]
