# Generated by Django 5.0 on 2024-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_alter_enviromenttitle_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pride',
            options={'verbose_name': 'Нам есть чем гордиться', 'verbose_name_plural': 'Нам есть чем гордиться'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'НАШИ ПРОЕКТЫ'},
        ),
    ]
