# Generated by Django 5.0 on 2024-02-22 17:25

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_contactinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='day/', verbose_name='Фотография дня')),
                ('night', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='day/', verbose_name='Фотография ночи')),
            ],
            options={
                'verbose_name': 'День и ночь',
                'verbose_name_plural': 'День и ночь',
            },
        ),
    ]
